
#server.port = ${GENERATED_CODE_SERVER_PORT}
DB_IDLETIMEOUT=0
DB_MAXLIFETIME=0
DB_CONNECTIONTIMEOUT=0
DB_MAXPOOLSIZE=50
DB_MINPOOLSIZE=50
KEEP_ALIVE=10

BATCH_SIZE=5000

#transientStoragePath=${TRANSIENT_STORAGE_PATH}

platform_1.0=true

#grpc.maxPoolSize = 1
#grpc.threads = 1

#grpc.server.port=9099

logging.level.com.sim.spriced=DEBUG

PLATFORM_TML_GRPC_MAX_POOLSIZE=10
GENERATED_CODE_SERVER_PORT=8085
DRIVER=${DB_DRIVER:org.postgresql.Driver}
TRANSIENT_STORAGE_PATH=C:/sim/storage















spring.application.name=transaction-management
spring.devtools.restart.enabled=false
server.port=${PLATFORM_TML_PORT_REST:8085}
grpc.client.monitor.address=static://localhost:9090
grpc.client.monitor.negotiationType=plaintext
PLATFORM_TML_PORT_GRPC=${PLATFORM_TML_PORT_GRPC:9095}
grpc.server.port=-1
grpc.client.Platform-client.address=${APPLICATION_GRPC_SERVER_ADDRESS:static://localhost:9097}
grpc.client.Platform-client.negotiationType=plaintext
grpc.maxPoolSize=${PLATFORM_TML_GRPC_MAX_POOLSIZE:1}
grpc.threads=${PLATFORM_TML_GRPC_THREADS:1}
batch.size=${BATCH_SIZE}
connection_timeout=${CONNECTION_TIMEOUT}
read_timeout=${READ_TIMEOUT}
auth.config.file=${PLATFORM_AUTH_CONFIG_FILE:auth-config.json}
transientStoragePath=${TRANSIENT_STORAGE_PATH}
excel.security.secret=${EXCEL_SECURITY_SECRET}
excel.security.algorithm=${EXCEL_SECURITY_ALGORITHM}
excel.sheet.password=${EXCEL_SHEET_PASSWORD}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
email.from=${EMAIL_FROM}
sheetPassword=${SHEETPASSWORD}
excel_generated_file_output_path=${EXCEL_GENERATED_FILE_OUTPUT_PATH}
outbound_processing_path=${OUTBOUND_PROCESSING_PATH}
outbound_faild_path=${OUTBOUND_FAILD_PATH}
email.subject.validation_failed=${EMAIL_SUBJECT_VALIDATION_FAILED}
email.body.validation_failed=${EMAIL_BODY_VALIDATION_FAILED}
email.message.mail_sent=${EMAIL_MESSAGE_MAIL_SENT}
email.message.mail_failed=${EMAIL_MESSAGE_MAIL_FAILED}
workflow.orchestrator.base-url=${WORKFLOW_ORCHESTRATOR_BASE_URL}
workflow.orchestrator.run-path=${WORKFLOW_ORCHESTRATOR_RUN_PATH}
workflow.orchestrator.workflowName=${WORKFLOW_ORCHESTRATOR_WORKFLOWNAME}
platform_1=true
spring.threads.virtual.enabled=true
server.tomcat.max-connections=10
INVALID_CELL_COLOR=${INVALID_CELL_COLOR}
MANDATORY_COLUMN_COLOR=${LIGHT_CORNFLOWER_BLUE}
VALID_MODIFIED_CELL_COLOR=${VALID_MODIFIED_CELL_COLOR}
LOCKED_COLUMNS_COLOR=${LOCKED_COLUMNS_COLOR}
HEADER_COLOR=${HEADER_COLOR}
EDITABLE_COLUMN_COLOR=${EDITABLE_COLUMN_COLOR}
transient.file.max.size=5KB
metadata.file.max.size=5KB



