server.port = 8085
DB_IDLETIMEOUT=${DB_IDLETIMEOUT}
DB_MAXLIFETIME=${DB_MAXLIFETIME}
DB_CONNECTIONTIMEOUT=${DB_CONNECTIONTIMEOUT}
DB_MAXPOOLSIZE=${DB_MAXPOOLSIZE}
DB_MINPOOLSIZE=${DB_MINPOOLSIZE}
KEEP_ALIVE=10

BATCH_SIZE=5000

transientStoragePath=${TRANSIENT_STORAGE_PATH}

platform_1.0=true

grpc.maxPoolSize = 1
grpc.threads = 1

grpc.server.port=9091

logging.level.com.sim.spriced=DEBUG

PLATFORM_TML_GRPC_MAX_POOLSIZE=1